replicaCount: 1

image:
  repository: https://artifactory.company.net/repo_name/superapp
  pullPolicy: IfNotPresent
  tag: "1.0"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
  hosts:
    - host: superapp.local
      paths:
        - path: /main
          pathType: Prefix

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetMemoryUtilizationPercentage: 80